# Generated by Django 3.0.7 on 2020-06-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
